steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
       '--build-arg', 'REACT_APP_GOOGLE_MAPS_API_KEY=${_REACT_APP_GOOGLE_MAPS_API_KEY}',
       '--build-arg', 'MONGODB_URI=${_MONGODB_URI}',
       '-t', '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest',
       '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest']

substitutions:
  _AR_HOSTNAME: asia-southeast1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _SERVICE_NAME: cultivo-capstone
  _MONGODB_URI: ${_MONGODB_URI}
  _REACT_APP_GOOGLE_MAPS_API_KEY: "" # Default empty, will be overridden by --substitutions flag

images:
  - '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest'